language: ruby
rvm:
  - 2.3.0

notifications:
  email: false

addons:
  postgresql: "9.4"

bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler

before_script:
  - psql -c 'create database posts_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:setup

gemfile:
  - Gemfile
