Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/**/*
    - config/initializers/*
    - config/environments/*
    - config/deploy/*
    - config/deploy.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/Encoding:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/Documentation:
  Enabled: false
